### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jschoch** [multigcs/riogui#2]
https://gist.github.com/jschoch/f5bf8cabf322f2b844d601b2c9fde26e

when clicking generate

```
  xcj.json
loading: xcj.json
loading board setup: TangNano9K
Traceback (most recent call last):
  File "/home/schoch/dev/riocore/../riogui/bin/rio-setup", line 1247, in generate
    project = riocore.Project(json.dumps(config, indent=4))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schoch/dev/riocore/riocore/__init__.py", line 260, in __init__
    self.generator_linuxcnc = LinuxCNC(self)
                              ^^^^^^^^^^^^^^
  File "/home/schoch/dev/riocore/riocore/generator/LinuxCNC.py", line 160, in __init__
    self.create_axis_config()
  File "/home/schoch/dev/riocore/riocore/generator/LinuxCNC.py", line 1668, in create_axis_config
    feedback_halname = f"rio.{position['halname']}"
                              ~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Aborted (core dumped)

```

**Comment by multigcs** [comment]
remove:   "is_joint" from  pwmout:
```
        {
            "type": "pwmout",
            "pins": {
                "pwm": {
                    "pin": "55"
                }
            },
            "name": "VOUT0",
            "frequency": 10000,
            "joint": {}
        },
```

**Comment by multigcs** [comment]
ohh, there is also another error, plese use:
```
PYTHONPATH=. bin/rio-generator test.json
```
not the button in the GUI, i try to fix it

**Comment by multigcs** [comment]
fixed in riocore

**Comment by jschoch** [comment]
```
schoch@lcncN3700:~/dev/riocore$ PYTHONPATH=. bin/python3 bin/rio-generator xcj.json 
loading: xcj.json
loading board setup: TangNano9K
Traceback (most recent call last):
  File "/home/schoch/dev/riocore/bin/rio-generator", line 26, in <module>
    project = riocore.Project(config_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schoch/dev/riocore/riocore/__init__.py", line 260, in __init__
    self.generator_linuxcnc = LinuxCNC(self)
                              ^^^^^^^^^^^^^^
  File "/home/schoch/dev/riocore/riocore/generator/LinuxCNC.py", line 160, in __init__
    self.create_axis_config()
  File "/home/schoch/dev/riocore/riocore/generator/LinuxCNC.py", line 1668, in create_axis_config
    feedback_halname = f"rio.{position['halname']}"
                              ~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jschoch** [comment]
ok, removing that is_joiht has  it working in the gui
